{% set name = "crococlean" %}
{% set version = "0.1.1" %}

package:
    name: {{ name }}
    version: {{ version }}


source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crococlean-{{ version }}.tar.gz 
  sha256: 357810ed1338732ad1441725f18b715beadf9b3110f561d4f527be5c07211cbe 

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps --no-cache-dir -vvv 
  entry_points:
    - crococlean = crococlean.crococlean:main
  run_exports:
    - {{ pin_subpackage('crococlean', max_pin="x.x") }}

requirements:
    host:
        - python >=3.12
        - poetry-core
        - pip
    run:
        - python >=3.12
        - pandas >=2.3
        - numpy >=2.4
        - tqdm >=4.67

test:
    commands:
        - crococlean --version

about:
  home: https://github.com/metagenopolis/CroCoClean
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: 'CroCoClean decontaminates species abundance profiles from metagenomic samples affected by cross-sample contamination'
  license_family: GPL3
